In [1]:
# Import the librarys
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
import tensorflow as tf
tf.__version__

'2.2.0'

In [3]:
#Load the data
data=pd.read_csv('../input/fake-news/train.csv')
data.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
#shape of data
data.shape

(20800, 5)

In [5]:
data.label.value_counts()

1    10413
0    10387
Name: label, dtype: int64

In [6]:
data.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [7]:
#drop the null values we do not fill any missing values with data
df=data.dropna()

In [8]:
df.reset_index(inplace=True)

In [9]:
x=df.iloc[:,:-1]
y=df['label']

In [10]:
y.value_counts()

0    10361
1     7924
Name: label, dtype: int64

In [11]:
x.shape

(18285, 5)

In [12]:
## One hot representation

import nltk
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords


In [13]:
message=x.copy()

In [14]:
message.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...  
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...  
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...  
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...

In [15]:
message['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [16]:
stemmer=PorterStemmer()
lemma=WordNetLemmatizer()

In [17]:
import re

In [18]:
corpus=[]
for i in range(0,len(message)):
    review=re.sub("[^a-zA-Z]"," ",message['title'][i])
    review=review.lower()
    review=review.split()
    ps=[stemmer.stem(word) for word in review if not word in stopwords.words('english')]
    ps=" ".join(ps)
    corpus.append(ps)

In [19]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
voc_size=5000

In [22]:
one_hot=[one_hot(words,voc_size) for words in corpus]
one_hot

[[264, 2628, 4320, 1092, 4414, 2686, 462, 4110, 4550, 3148],
 [419, 4957, 642, 3711, 948, 1324, 3365],
 [3002, 4040, 4497, 1262],
 [1557, 1071, 1372, 2862, 1768, 1636],
 [3353, 948, 4779, 4123, 472, 3946, 948, 1782, 2746, 1336],
 [171,
  717,
  1560,
  3389,
  2529,
  4150,
  4413,
  4662,
  3478,
  1682,
  861,
  4321,
  3254,
  1943,
  3365],
 [520, 1618, 235, 3226, 1862, 3607, 2718, 71, 850, 1947, 3376],
 [4629, 1226, 3349, 4091, 3990, 335, 4150, 638, 850, 1947, 3376],
 [779, 3191, 1588, 3645, 1923, 901, 4075, 1358, 4150, 3028],
 [4817, 703, 4188, 3488, 4332, 3213, 2668, 3213],
 [4012, 2569, 948, 4865, 3727, 1627, 3629, 90, 1656, 4351, 2820],
 [2862, 3074, 4414, 901, 4150, 3990],
 [863, 3562, 2116, 3211, 4266, 40, 1293, 4890, 2439],
 [4355, 2659, 2262, 2261, 4533, 2577, 4773, 850, 1947, 3376],
 [3428, 4443, 4963, 4977, 1811, 850, 1947, 3376],
 [537, 344, 570, 2341, 969, 3965, 1338, 2554, 4635, 885],
 [1030, 923, 4957],
 [4232, 2692, 3637, 3961, 4150, 1202, 3430, 3365],
 [3631, 4006,

## Embedding Representation

In [23]:
sent_length=20
embed_doc=pad_sequences(one_hot,padding='pre',maxlen=sent_length)
embed_doc

array([[   0,    0,    0, ..., 4110, 4550, 3148],
       [   0,    0,    0, ...,  948, 1324, 3365],
       [   0,    0,    0, ..., 4040, 4497, 1262],
       ...,
       [   0,    0,    0, ...,  850, 1947, 3376],
       [   0,    0,    0, ...,  751, 1056, 3560],
       [   0,    0,    0, ..., 4222, 1388,  989]], dtype=int32)

In [24]:
embed_doc[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  264,
       2628, 4320, 1092, 4414, 2686,  462, 4110, 4550, 3148], dtype=int32)

In [25]:
from tensorflow.keras.layers import LSTM

In [26]:
#Create a moodel
dim=40
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
#Compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [28]:
len(embed_doc)

18285

In [29]:
len(y)

18285

In [30]:
x_final=np.array(embed_doc)
y_final=np.array(y)

In [31]:
print(x_final.shape,y_final.shape)

(18285, 20) (18285,)


In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.3,random_state=43)

In [33]:
#model training
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
200/200 [==============================] - 6s 29ms/step - loss: 0.0013 - accuracy: 0.9997 - val_loss: 0.0012 - val_accuracy: 0.9996
Epoch 2/10
200/200 [==============================] - 5s 27ms/step - loss: 1.6721e-04 - accuracy: 1.0000 - val_loss: 0.0010 - val_accuracy: 0.9996
Epoch 3/10
200/200 [==============================] - 5s 27ms/step - loss: 9.8713e-05 - accuracy: 1.0000 - val_loss: 9.4753e-04 - val_accuracy: 0.9998
Epoch 4/10
200/200 [==============================] - 5s 26ms/step - loss: 7.2797e-05 - accuracy: 1.0000 - val_loss: 9.2136e-04 - val_accuracy: 0.9998
Epoch 5/10
200/200 [==============================] - 5s 27ms/step - loss: 5.6471e-05 - accuracy: 1.0000 - val_loss: 9.1370e-04 - val_accuracy: 0.9998
Epoch 6/10
200/200 [==============================] - 5s 27ms/step - loss: 4.5391e-05 - accuracy: 1.0000 - val_loss: 8.9301e-04 - val_accuracy: 0.9998
Epoch 7/10
200/200 [==============================] - 6s 28ms/step - loss: 3.7288e-05 - accuracy: 1.0000 -

In [34]:
y_pred=model.predict_classes(x_test)

In [35]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test,y_pred))

[[3152    1]
 [   0 2333]]


In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3153
           1       1.00      1.00      1.00      2333

    accuracy                           1.00      5486
   macro avg       1.00      1.00      1.00      5486
weighted avg       1.00      1.00      1.00      5486



In [37]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9998177178271965
